#!/bin/bash
# My First Script
declare -a filenametxt=(areasofthefield.txt auxiliaryplayerequipment.txt)
declare -a filenamehtml=(areasofthefield.html auxiliaryplayerequipment.html)
#for i,j in ${filenametxt[@]} ${filenamehtml[@]}
for (( i=0; i<2; i++))
do
	txtfile=${filenametxt[$i]}
	htmlfile=${filenamehtml[$i]}
	value=`cat $txtfile`
	sqlite3 usaf_rules_demo "update demo set title=\"$value\" where name=\"$htmlfile\";"
	echo "$value"
done
