#!/bin/bash
for htmlfile in *.html; do
        scratchbase='/tmp/temp'
        cp $htmlfile $scratchbase.txt
        echo "Processing file $htmlfile"
    	sed '/<script/,/<\/script>/d' $scratchbase.txt > $scratchbase.2.txt  $scratchbase.2.txt
        value=`cat $scratchbase.2.txt`
        #sqlite3 usaf_rules "update rules set content=\"$value\" where path=\"$htmlfile\";"
        rm $scratchbase.*
        echo "$value"
done
