#!/bin/bash
declare filenametxt=textformat.txt

declare -a filenamehtml=(
areasofthefield.html
authorityanddutiesofthereferee.html
)

for (( i=0; i<1; i++))
do
	htmlfile=${filenamehtml[$i]}
	abiword --to=txt $htmlfile	
	#sed -i 's/"/ /g' ${filenametxt[$i]}
	#txtfile=${filenametxt[0]}
	#value=`cat $htmlfile`
	echo "$htmlfile"
	#sqlite3 usaf_rules "update rules set content=\"$value\" where path=\"$htmlfile\";"
	#echo "$htmlfile"
done
